### ISSUE TITLE
[FEAT] change model type heuristic - update to check the label column/dataset type instead of just proba

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#2054] opened 2022-09-22 14:19 UTC
**Is your feature request related to a problem? Please describe.**
Currently we decide if a model is a classification model if it has proba function attribute.

**Describe the solution you'd like**
I want the model type to check the label column/dataset type if the proba function doesn't exists

**Comment by noamzbr** [comment] 2022-09-22 14:40
Duplicate of https://github.com/deepchecks/deepchecks/issues/2053

**Closed by noamzbr** 2022-09-22 14:40 UTC
Labels: feature, needs triage
