### ISSUE TITLE
[BUG] Some checks still crashes kernel in train test validation suite

### ISSUE THREAD

**Issue by DL1992** [deepchecks/deepchecks#1689] opened 2022-06-27 14:31 UTC
Describe the bug
When running checks/suits involving calculating feature importance the notebook kernel crash.
This happens when running Whole Dataset Drift and Train Test Prediction Drift
both checks only fail if the time for calculating FI is not limited. when it is limited  to 0 they don't crash the notebook

To Reproduce
Sadly, I can't give a sample of the dataset.
it's about 1M rows with 50 columns (both categorical and numeric)
RAM size is very large (over 1TB) - multiple CPU cores

Running tests with permutation_importance calculation crash notebook kernel - the status of the test hangs for a bit and after 1 minute the notebook kernel crashes and needs to be restarted. It only happens when deepchecks is calculating features importance for me. there is no problem when running a model like XGBOOST which calculates feature importance.
Expected behavior
Checks/Suites should run and not crash the notebook kernel

Screenshots

Environment (please complete the following information):

OS: linux
Python Version:3.7.3
Deepchecks Version:0.8.0
Additional context

**Comment by JKL98ISR** [comment] 2022-06-28 09:05
Hi, Whole Dataset Drift and Train Test Prediction Drift do not calculate FI (Whole Dataset Drift dies but it is internal and isn't affected by the user params).
Maybe you meant TrainTestFeatureDrift?

**Comment by ItayGabbay** [comment] 2022-07-18 13:17
Closing this because it cannot be reproduced. @DL1992 if this happens again, feel free to reopen

**Closed by ItayGabbay** 2022-07-18 13:17 UTC
Labels: bug, needs triage
